version: "3"

services:
  note_db:
    image: mongo:4.2
    volumes:
      - note_mongodb:/data/db
      - note_mongodb_config:/data/configdb
  note_web:
    build: .
    volumes:
      - .:/code
    ports:
      - "21702:21702"
    depends_on:
      - note_db

volumes:
  note_mongodb:
  note_mongodb_config:
