kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mongodb-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-container
  template:
    metadata:
      labels:
        app: mongodb-container
        tier: backend
    spec:
      containers:
        - name: mongodb-container
          image: mongo:4-bionic
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: mongodb-volume-mount
              mountPath: /data/db

      volumes:
        - name: mongodb-volume-mount
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb-container
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
